server:
  port: 8899
spring:
  datasource:
    url: jdbc:mysql://192.168.23.200:3306/test_db?characterEncoding=utf8&useSSL=false
    username: dhy
    password: 123456
  quartz:
    job-store-type: jdbc
    jdbc:
      # 每次启动都初始化quartz相关表
     initialize-schema: always
     schema: classpath:schema/tables_mysql.sql
    properties:
      # 命名空间
      org.quartz.scheduler.instanceName: ClusterQuartz
      # 集群id
      org.quartz.scheduler.instanceId: AUTO
      #数据保存方式为持久化
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.clusterCheckinInterval: 20000
      org.quartz.jobStore.maxMisfiresToHandleAtATime: 1
      #容许的最大作业延长时间
      org.quartz.jobStore.misfireThreshold: 120000
      #这能助于防止某些数据库在高负荷和长事物时的锁超时。
      org.quartz.jobStore.txIsolationLevelSerializable: true
  redis:
    port: 6379
    host: 192.168.23.200
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.demo.domain
logging:
  level:
    com.exmaple.demo: debug